### ISSUE TITLE
Change alert Messages? (Ideal)

### ISSUE THREAD

**Issue by ZippingBoat9588** [Tobias-2006/ClearLag#6]
Can you please add in config.yml that we can set the times manually? @Tobias-2006 
Like this

# Here you can Set the alert Messages example 1s= 1 Second 1m= 1 Minute 
Times: 1s, 2s, 5s, 10s, 1m

Or can you say ne how i can Change it in your Plugin?
LG zip

**Comment by ZippingBoat9588** [comment]
I want only These alerts: 1minute, 30 Seconds, 10 Seconds, 5 Seconds, 4,3,2,1 you know

**Comment by ZippingBoat9588** [comment]
Wow Just ignore me .-.

**Comment by tobiaskirchmaier** [comment]
In the current version, the notification times are hardcoded into the source code. In the next update I will follow your request and make it possible to change them. Since I'm currently rather busy with other things, as you have unfortunately already noticed, I would be happy if you (or someone who reads this) implements this possibility and opens a pull request.

**Comment by UnknownNull** [comment]
not work
